/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfeapplication;

import java.awt.Toolkit;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.sql.Date;
import java.sql.ResultSetMetaData;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PC-ASUS
 */
public class AjoutPatient extends javax.swing.JFrame {

    /**
     * Creates new form AjoutPatient
     */
    Connexion cnx;//=new Connexion();
    Connection con;
    Calendar calendar = Calendar.getInstance( );
 SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    java.sql.Date parsed = null;
    Date Maxdate;
    public String indice;
Date dt;

    public AjoutPatient() throws ClassNotFoundException, SQLException {
        initComponents();
        setIcone();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("phar3.png")));
        setTitle("Ajouter Patient");
       /*this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        for(int i=1;i<32;i++)
            jours.addItem(i);
        for(int j=1;j<13;j++)
            moin.addItem(j);
        for(int k=1900;k<2016;k++)
            anne.addItem(k);*/
        tappedpane.removeAll();
        tappedpane.add(jPanel7);
        remplir_combo(diag1,"select distinct diag1 from hospital");
        remplir_combo(diag2,"select distinct diag2 from hospital");
          remplir_combo(cat,"select distinct cat from hospital");
          remplir_combo(antibiotique,"select ref from antibiotique");
          remplir_combo(listacte,"select libact from acte " );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtind = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        gest_act = new javax.swing.JButton();
        gest_pass1 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        antibiotique1 = new javax.swing.JButton();
        ajout_acte1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tappedpane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtprenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtsex = new javax.swing.JComboBox();
        btnreset = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        txt_dn = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        hop = new javax.swing.JRadioButton();
        dom = new javax.swing.JRadioButton();
        nom_pat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        detorig = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cat = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        knuas = new javax.swing.JTextField();
        ind_pat2 = new javax.swing.JTextField();
        saps = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        listeprisant = new javax.swing.JComboBox();
        cissue = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        dsj = new javax.swing.JTextField();
        infection = new javax.swing.JComboBox();
        age = new javax.swing.JTextField();
        diag1 = new javax.swing.JComboBox();
        diag2 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        dos_pat = new javax.swing.JTextField();
        dentrea = new com.toedter.calendar.JDateChooser();
        denth = new com.toedter.calendar.JDateChooser();
        dsortrea = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        nompatient = new javax.swing.JLabel();
        indicepatient = new javax.swing.JLabel();
        dossierpatient = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dosage = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        date_anti = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        antibiotique = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        motif = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        ajout_antiPanel = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtref = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtlibel = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtdose = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        affectact = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        txtdosacte = new javax.swing.JTextField();
        listacte = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        date_acte = new com.toedter.calendar.JDateChooser();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        nompatient1 = new javax.swing.JLabel();
        dossierpatient1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton20 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Close-32x32 - Copie.png"))); // NOI18N
        jButton2.setText("Quitter");
        jButton2.setActionCommand("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 600, 140, 47));
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 90, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gestion des patient", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 18), new java.awt.Color(51, 0, 204))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 507, 179, 45));

        jButton7.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/azer.jpg"))); // NOI18N
        jButton7.setText("Chercher");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 93, 153, 40));

        jButton8.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/azer.jpg"))); // NOI18N
        jButton8.setText("Visualisation");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 510, 153, 40));
        jPanel1.add(txtind, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 120, 30));

        jLabel23.setText("Entrer ind: ");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        gest_act.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/azer.jpg"))); // NOI18N
        gest_act.setText("affecter acte");
        gest_act.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gest_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gest_actActionPerformed(evt);
            }
        });
        jPanel1.add(gest_act, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 270, 153, 40));

        gest_pass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/azer.jpg"))); // NOI18N
        gest_pass1.setText("Gestion patient");
        gest_pass1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gest_pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gest_pass1ActionPerformed(evt);
            }
        });
        jPanel1.add(gest_pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 151, 153, 40));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/azer.jpg"))); // NOI18N
        jButton19.setText("Ajouter antibiotique");
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 380, 153, 40));

        antibiotique1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/azer.jpg"))); // NOI18N
        antibiotique1.setText("Affecter antibiotique");
        antibiotique1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        antibiotique1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antibiotique1ActionPerformed(evt);
            }
        });
        jPanel1.add(antibiotique1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 210, 153, 40));

        ajout_acte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/azer.jpg"))); // NOI18N
        ajout_acte1.setText("ajouter acte");
        ajout_acte1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(ajout_acte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 440, 153, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/azer.jpg"))); // NOI18N
        jButton4.setText("Hospitalisation");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 320, 153, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 570));
        jPanel1.getAccessibleContext().setAccessibleName("Gestion des patients");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 52, 30));

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        jPanel2.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 172, 30));

        jLabel2.setText("Prenom:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 52, 30));
        jPanel2.add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 172, 30));

        jLabel3.setText("Date de naissance:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 100, 30));

        jLabel4.setText("Sex:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 60, 40));

        txtsex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculin  ", "Féminin   " }));
        jPanel2.add(txtsex, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 176, 30));

        btnreset.setText("Annuler");
        jPanel2.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 121, 35));

        jButton9.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouter-une-liste-personne-utilisateur-icone-8190-32.png"))); // NOI18N
        jButton9.setText("Ajouter");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 115, 39));

        jButton10.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprimer-un-utilisateur-icone-4165-32.png"))); // NOI18N
        jButton10.setText("supprimer ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, 37));

        jButton12.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modifier.png"))); // NOI18N
        jButton12.setText("Modifier");
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 115, 40));

        txt_dn.setDateFormatString("yyyy-dd-MM");
        jPanel2.add(txt_dn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 170, 30));

        tappedpane.addTab("Gestion Patient", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hop.setText("Hop");
        hop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hopActionPerformed(evt);
            }
        });
        jPanel3.add(hop, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 381, 64, -1));

        dom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dom.setText("Dom");
        dom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domActionPerformed(evt);
            }
        });
        jPanel3.add(dom, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 381, 57, -1));

        nom_pat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.add(nom_pat, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 33, 139, 25));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Saps");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 166, 149, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Knuas");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 132, 149, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Categorie");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 87, 149, 23));
        jPanel3.add(detorig, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 425, 139, 24));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Age");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 196, 156, 27));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Durée sejour");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 155, 156, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Dossier de Patient");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 122, 156, 29));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Indice");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 86, 156, 23));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Diagnostic2");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 380, 149, -1));

        jPanel3.add(cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 89, 149, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Infection");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 289, 149, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fleches-interagir-recharger-mise-a-jour-icone-5225-32.png"))); // NOI18N
        jButton5.setText("Actialiser");
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 459, 149, 37));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Diagnostic1");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 341, 149, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Cissue");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 198, 149, 24));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("priseAntibiotique");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 241, 149, 26));

        knuas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knuasActionPerformed(evt);
            }
        });
        jPanel3.add(knuas, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 122, 149, 25));

        ind_pat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ind_pat2ActionPerformed(evt);
            }
        });
        jPanel3.add(ind_pat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 88, 139, 23));
        jPanel3.add(saps, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 158, 149, 23));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Detorig");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 425, 156, 27));

        listeprisant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oui", "Non" }));
        jPanel3.add(listeprisant, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 241, 149, 26));
        jPanel3.add(cissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 199, 149, 24));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Date d'entré hopital");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 289, 156, 27));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Date d'entré reamination");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 244, 156, 25));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Origine");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 378, 156, 29));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Date sortie hopital");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 337, 156, 23));
        jPanel3.add(dsj, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 158, 139, 23));

        infection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oui", "Non" }));
        jPanel3.add(infection, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 287, 149, -1));

        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel3.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 199, 140, 24));

        diag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diag1ActionPerformed(evt);
            }
        });
        jPanel3.add(diag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 339, 149, -1));

        jPanel3.add(diag2, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 378, 149, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ajouter-une-liste-personne-utilisateur-icone-8190-32.png"))); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 459, 156, 37));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprimer-un-utilisateur-icone-4165-32.png"))); // NOI18N
        jButton3.setText("Supprimer");
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 459, 139, 37));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modifier.png"))); // NOI18N
        jButton11.setText("Modifier");
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 459, 149, 37));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("Nom patient");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 32, 156, 25));
        jPanel3.add(dos_pat, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 122, 139, 25));
        jPanel3.add(dentrea, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 140, 30));
        jPanel3.add(denth, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 140, 30));
        jPanel3.add(dsortrea, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 140, 30));

        tappedpane.addTab("Gestion dossier médicales", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nompatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nompatient.setText("Nom:");
        jPanel4.add(nompatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 64, 160, 33));

        indicepatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(indicepatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 140, 31));

        dossierpatient.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dossierpatient.setText("Dossier:");
        jPanel4.add(dossierpatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 180, 30));

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton13.setText("Affecter");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 110, 34));

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton14.setText("Modifier");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 120, 34));

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton15.setText("Supprimer");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 120, 34));

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton16.setText("Actialiser");
        jPanel4.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 120, 34));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(51, 51, 51));
        jTable1.setRowMargin(5);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 470, 310));
        jPanel4.add(dosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 150, 30));

        jLabel27.setText("Dose");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));
        jPanel4.add(date_anti, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 150, 30));

        jLabel28.setText("Date");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        jPanel4.add(antibiotique, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 150, 30));

        jLabel29.setText("antibiotique");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 70, 30));
        jPanel4.add(motif, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 150, 30));

        jLabel30.setText("Motif");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 50, 20));

        jLabel35.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 0, 0));
        jLabel35.setText("Affecter antibiotique ");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 280, 30));

        tappedpane.addTab("Gestion antibiotique", jPanel4);

        ajout_antiPanel.setBackground(new java.awt.Color(255, 255, 255));
        ajout_antiPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("Ajouter nouveau antibiotique");
        ajout_antiPanel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 26, 258, 39));

        jLabel32.setText("Ref:");
        ajout_antiPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 162, 61, 25));
        ajout_antiPanel.add(txtref, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 156, 28));

        jLabel33.setText("Libellé:");
        ajout_antiPanel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 198, 63, 29));

        txtlibel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlibelActionPerformed(evt);
            }
        });
        ajout_antiPanel.add(txtlibel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 198, 156, 29));

        jLabel34.setText("dose:");
        ajout_antiPanel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 238, 48, 25));
        ajout_antiPanel.add(txtdose, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 238, 156, 25));

        jButton6.setText("Ajouter");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        ajout_antiPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 310, 100, 37));

        jButton17.setText("Annuler");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        ajout_antiPanel.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 310, 108, 37));

        tappedpane.addTab("Ajouter antibiotique", ajout_antiPanel);

        affectact.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        jLabel36.setText("Dossier patient");

        jLabel37.setText("Liste acte");

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dossier-deplacer-icone-9385-32_1.png"))); // NOI18N
        jButton18.setText("Affecter");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jLabel38.setText("Date");

        jLabel39.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 0, 0));
        jLabel39.setText("Affecter acte");

        nompatient1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nompatient1.setText("Nom:");

        dossierpatient1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dossierpatient1.setText("Dossier:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.setGridColor(new java.awt.Color(51, 51, 51));
        jTable2.setRowMargin(5);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton20.setText("Supprimer");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(46, 46, 46)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date_acte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listacte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdosacte)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(nompatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dossierpatient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(178, 178, 178))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nompatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dossierpatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel36))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(txtdosacte, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listacte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(date_acte, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout affectactLayout = new javax.swing.GroupLayout(affectact);
        affectact.setLayout(affectactLayout);
        affectactLayout.setHorizontalGroup(
            affectactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(affectactLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        affectactLayout.setVerticalGroup(
            affectactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, affectactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tappedpane.addTab("Affecter acte", affectact);

        jLabel24.setText("cacte:");

        jLabel25.setText("Libellé:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        tappedpane.addTab("Ajouter acte", jPanel5);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/medical.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 552, Short.MAX_VALUE)
        );

        tappedpane.addTab("", jPanel7);

        getContentPane().add(tappedpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 820, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
public void remplir_hos(String ind) throws ClassNotFoundException, SQLException
{ cnx=new Connexion();
    con=cnx.connect();
            //Statement stmt = con.createStatement();
        
 String req="Select h.* from hospital h, patient p Where h.ind=p.ind and p.ind=?";

            PreparedStatement st=con.prepareStatement(req);

            st.setString(1, ind);

            ResultSet rs = st.executeQuery();
nom_pat.setText(txtnom.getText().trim()+" "+txtprenom.getText());ind_pat2.setText(ind);
            while(rs.next()){
                //               nompat.setText(rs1.getString(2));

                dos_pat.setText(rs.getString(1));
                dsj.setText(rs.getString(2));
                age.setText(rs.getString(3));
               
                ((JTextField)dentrea.getDateEditor().getUiComponent()).setText(rs.getString(4));
                ((JTextField)denth.getDateEditor().getUiComponent()).setText(rs.getString(5));
                ((JTextField)dsortrea.getDateEditor().getUiComponent()).setText(rs.getString(6));
                if(rs.getString("orig").trim().equals("Dom"))
                dom.setSelected(true);
                if(rs.getString("orig").trim().equals("Hop"))
                hop.setSelected(true);

                detorig.setText(rs.getString(8).substring(1,10));
                listeprisant.setSelectedItem(rs.getString(9));
                cat.addItem((Object)(rs.getString(10)));
                knuas.setText(rs.getString(11));
                saps.setText(rs.getString(12));
                cissue.setText(rs.getString(14));
                infection.setSelectedItem(rs.getString(15));
                diag1.setSelectedItem(rs.getString("diag1"));
                diag2.setSelectedItem(rs.getString("diag2"));

            }
        
        //JOptionPane.showMessageDialog(null,"Dossier trouvé");




}
 public void remplir_combo(JComboBox comb, String req) throws ClassNotFoundException, SQLException {
       con=cnx.connect();
        Statement st =con.createStatement();
      //  JComboBox Jbox = new JComboBox();
       
         
        //String sql = "SELECT ind FROM patient";
        ResultSet Rs = null;
        try {
            Rs = st.executeQuery(req);
        } catch (SQLException ex) {
            System.out.println("Erreur Requête");
        }
       try {
            while (Rs.next()) {
                
                
               comb.addItem(Rs.getString(1).trim());
               
                
             //   System.out.println(Rs.getString("nom"));
            }
        } catch (SQLException ex) {
                System.out.println("Erreur Rs");
        }
 }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            con=cnx.connect();
            Statement st1 = con.createStatement();

            String Query = "select * from patient where ind ='"+txtind.getText()+"'";
            ResultSet rs1;
            rs1 = st1.executeQuery(Query);
            while(rs1.next()) {
                String nom = rs1.getString("nom");//+" "+rs1.getString("pre");
                System.out.println(nom);
                txtnom.setText(nom);
                txtprenom.setText(rs1.getString("pre"));
            indice=rs1.getString("ind");
            //   calendar.setTime(rs1.getDate("dn"));
             
            ((JTextField)txt_dn.getDateEditor().getUiComponent()).setText(rs1.getString("dn"));

            
             
              String s=rs1.getString("sex");
              txtsex.setSelectedItem(s);
              remplir_hos(txtind.getText());
              GestionAntibio(dos_pat.getText());
              
      
//+"\n"+rs1.getDate("dn"));
            //paintComponent(jPanel1.getGraphics());*/
        } // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(gestionpatient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(gestionpatient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Visualisation v = null;
        try {
            v = new Visualisation(txtind.getText());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(gestionpatient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(gestionpatient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(gestionpatient.class.getName()).log(Level.SEVERE, null, ex);
        }
        v.show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed
public void GestionAntibio(String dos) throws SQLException, ClassNotFoundException
{
             nompatient.setText("nom: "+txtnom.getText());
    indicepatient.setText("indice: "+txtind.getText());
    dossierpatient.setText("dossier: "+dos_pat.getText());
   con=cnx.connect();
 String req="select pr.* from presAnti pr, hospital h where h.dos=pr.dos and h.dos='"+dos+"'";
//String req2="select a.* from antibiotique a"
            Statement st=con.createStatement();
           
          //  DefaultTableModel aModel = (DefaultTableModel) aTable.getModel();
         
            ResultSet rs = st.executeQuery(req);
          int nbline=getNbligne(dos);
 String col[] ={ "dossier", "antibiotique", "dosage", "motif", "date" };
             String cont[][] = new String[nbline][5];
      int i = 0;
      while (rs.next()) {
        String dosier= rs.getString(1).trim();
        String anti = rs.getString(2).trim();
    String dose=rs.getString(3).trim();
    String motif=rs.getString(4).trim();
    String dat=rs.getString(5);
        
        cont[i][0] = dosier;
        cont[i][1] = anti;
        cont[i][2] = dose;
        cont[i][3] = motif;
        cont[i][4] = dat;
        i++;
      }
    
      DefaultTableModel model = new DefaultTableModel(cont,col);
  jTable1.setModel(model);

   // System.out.println("Maxdate= "+Maxdate);

            
            

}
String act[];
public void getionActe() throws ClassNotFoundException, SQLException
{
  nompatient1.setText(nompatient1.getText()+txtnom.getText().trim());
 
    dossierpatient1.setText(dossierpatient1.getText()+dos_pat.getText().trim());
String req="select  h.dos, a.libact, v.dact, a.cacte from verifierActe v, acte a, hospital h, patient p where a.cacte=v.cacte\n" +
" and v.dos=h.dos and p.ind=h.ind and  p.ind ='"+indice+"' order by v.dact";

con=cnx.connect();
Statement st =con.createStatement();
ResultSet rs=st.executeQuery(req);
int nbligne=getnbact();
 String col[] ={ "dossier", "Acte", "date" };
             String cont[][] = new String[nbligne][4];
              act=new String[nbligne];
      int i = 0;
      while (rs.next()) {
        String dosier= rs.getString(1).trim();
        String acte = rs.getString(2).trim();
    String date=rs.getString(3).trim();
    String cact=rs.getString("cacte");
        
        cont[i][0] = dosier;
        cont[i][1] = acte;
        cont[i][2] = date;
       act[i]=cact;
        i++;
      }
    
      DefaultTableModel model = new DefaultTableModel(cont,col);
  jTable2.setModel(model);
 

  
  //jTable1.removeColumn(jTable1.getColumnModel().getColumn(3));
}

public int getNbligne(String dossier) throws ClassNotFoundException, SQLException
{
String req="select count(p.dos) as nb from presAnti p, hospital h where p.dos=h.dos and h.dos='"+dossier+"'";
con=cnx.connect();
int nb = 0;
Statement st =con.createStatement();
ResultSet rs=st.executeQuery(req);
while(rs.next()){
nb=rs.getInt("nb");
}
return nb;


}
public int getnbact() throws ClassNotFoundException, SQLException
{
String req="select count(h.dos) as nb from verifierActe v, acte a, hospital h, patient p where a.cacte=v.cacte\n" +
" and v.dos=h.dos and p.ind=h.ind and  p.ind ='"+indice+"'";
con=cnx.connect();
int nb = 0;
Statement st =con.createStatement();
ResultSet rs=st.executeQuery(req);
while(rs.next()){
nb=rs.getInt("nb");
}
return nb;

}
public void insert_hostipal() throws SQLException, ClassNotFoundException
{
    con=cnx.connect();
String req="insert into hospital values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
PreparedStatement st=con.prepareStatement(req);
st.setString(1, dos_pat.getText());
st.setString(2,dsj.getText());
st.setString(3, age.getText());
java.sql.Date dent = new java.sql.Date(dentrea.getDate().getTime());
st.setDate(4, dent);
java.sql.Date denthos=new java.sql.Date(denth.getDate().getTime());
st.setDate(5, denthos);
java.sql.Date dsorea =new java.sql.Date(dsortrea.getDate().getTime());
st.setDate(6, dsorea);
if(dom.isSelected())
st.setString(7, "DOM");
else
    st.setString(7, "HOP");
st.setString(8, detorig.getText());
st.setString(9, listeprisant.getSelectedItem().toString());
st.setString(10, cat.getSelectedItem().toString());
st.setString(11, knuas.getText());
st.setString(12, saps.getText());
st.setString(13,ind_pat2.getText());
st.setString(14, cissue.getText());
st.setString(15, infection.getSelectedItem().toString());
st.setString(16, diag1.getSelectedItem().toString());
st.setString(17,diag2.getSelectedItem().toString());
st.executeUpdate();

}
    private void gest_pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gest_pass1ActionPerformed
        // TODO add your handling code here:
        tappedpane.add(jPanel2,"gestion patient");
         tappedpane.setSelectedComponent(jPanel2);
    }//GEN-LAST:event_gest_pass1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        tappedpane.add(jPanel3,"gestion dossier médicale");
        tappedpane.setSelectedComponent(jPanel3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void antibiotique1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antibiotique1ActionPerformed
        // TODO add your handling code here:
        tappedpane.add(jPanel4,"affecter antibiotique");
        tappedpane.setSelectedComponent(jPanel4);
      /* 
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
         jTable1.getColumnModel().getColumn(0).setMinWidth(0);
          jTable1.getColumnModel().getColumn(0).setWidth(0);*/
        //jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));
        
    }//GEN-LAST:event_antibiotique1ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
         tappedpane.add(ajout_antiPanel,"Ajouter antibiotique");
        tappedpane.setSelectedComponent(ajout_antiPanel);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void gest_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gest_actActionPerformed
tappedpane.add(affectact,"affecter acte");
        tappedpane.setSelectedComponent(affectact);     
        try {
            // TODO add your handling code here:
            getionActe();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AjoutPatient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AjoutPatient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gest_actActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        try {
            // TODO add your handling code here:
            con=cnx.connect();
            java.sql.Statement stmt = con.createStatement();
            String req="Insert into verifierActe (cacte, dos, dact)Values(?, ?, ?)";
            PreparedStatement stm=con.prepareStatement(req);
            String ab=listacte.getSelectedItem().toString();
            stm.setString(1,ab);

            stm.setString(2,txtdosacte.getText());
            java.sql.Date d=new java.sql.Date(date_acte.getDate().getTime());
            stm.setDate(3, d);

            stm.execute();
        } catch (SQLException ex) {
            Logger.getLogger(AjoutPatient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AjoutPatient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        txtref.setText(null);
        txtlibel.setText(null);
        txtdose.setText(null);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{    con=cnx.connect();
            String req="insert into antibiotique values(?,?,?)";
            PreparedStatement ps=con.prepareStatement(req);
            ps.setString(1,txtref.getText());
            ps.setString(2, txtlibel.getText());
            ps.setFloat(3, Float.parseFloat(txtdose.getText()));
            ps.executeUpdate();

        }catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtlibelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlibelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlibelActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int ligne= jTable1.getSelectedRow();
        motif.setText(jTable1.getValueAt(ligne,3).toString());
        antibiotique.setSelectedItem(jTable1.getValueAt(ligne, 1).toString());
        dosage.setText(jTable1.getValueAt(ligne,2).toString());
        java.util.Date datt = null;
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        try {
            datt = formatter.parse(jTable1.getValueAt(ligne,4).toString());
        } catch (ParseException ex) {
            Logger.getLogger(AjoutPatient.class.getName()).log(Level.SEVERE, null, ex);
        }
        date_anti.setDate(datt);
System.out.println("nb colonne"+jTable1.getColumnCount());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try {
            // TODO add your handling code here:
            con=cnx.connect();

            java.sql.Date dateanti =new java.sql.Date(date_anti.getDate().getTime());
            String req="update presAnti set dose='"+dosage.getText()+"', motif='"+
            motif.getText()+"' where dos='"+dos_pat.getText()+"' and ref='"+antibiotique.getSelectedItem().toString()+"' and dt='"+dateanti+"'";
            Statement st;

            st = con.createStatement();

            st.execute(req);
            GestionAntibio(dos_pat.getText());
        } catch (SQLException ex) {
        } catch (ClassNotFoundException ex) {
        }
        jTable1.repaint();

    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try{ con=cnx.connect();
            String req="insert into presAnti values(?,?,?,?,?)";
            PreparedStatement st=con.prepareStatement(req);
            st.setString(1, dos_pat.getText());
            st.setString(2, antibiotique.getSelectedItem().toString());
            st.setString(3, dosage.getText());
            st.setString(4, motif.getText());
            java.sql.Date d =new java.sql.Date(date_anti.getDate().getTime());
            st.setDate(5, d);
            st.executeUpdate();
        }catch (Exception e)
        {

        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        
        indicepatient.setText("indice: "+ind_pat2.getText());
        nompatient.setText("nom :"+nom_pat.getText());
        //  dosa.setText(dos_pat.getText());
        dossierpatient.setText("dossier: "+dos_pat.getText());
        try {
            // TODO add your handling code here:
            insert_hostipal();
        } catch (SQLException ex) {
        } catch (ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void diag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diag1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diag1ActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void ind_pat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ind_pat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ind_pat2ActionPerformed

    private void knuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knuasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_knuasActionPerformed

    private void domActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domActionPerformed
        // TODO add your handling code here:
        hop.setSelected(false);
    }//GEN-LAST:event_domActionPerformed

    private void hopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hopActionPerformed
        // TODO add your handling code here:
        dom.setSelected(false);
    }//GEN-LAST:event_hopActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        supprimerpatient sp = new supprimerpatient();
        sp.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        java.util.Date jud =txt_dn.getDate();
        java.sql.Date sqd=new java.sql.Date(jud.getTime());
        try {

            con=cnx.connect();

            String req="insert into patient(ind,nom,pre,dn,sex) values('"+txtind.getText()+"', '"+txtnom.getText()+"', '"+txtprenom.getText()+
            "', '"+sqd+"', '"+txtsex.getSelectedItem()+"')";
            Statement st=con.createStatement();
            if(st.execute(req))
            System.out.println("Succccéééééé");

            nom_pat.setText(txtnom.getText().trim()+" "+txtprenom.getText());ind_pat2.setText(txtind.getText().trim());

        } catch (SQLException ex) {
        } catch (ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int ligne= jTable2.getSelectedRow();
        txtdosacte.setText(jTable2.getValueAt(ligne,0).toString());
        listacte.setSelectedItem(jTable2.getValueAt(ligne, 1).toString());
        
        java.util.Date datt = null;
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        try {
            datt = formatter.parse(jTable2.getValueAt(ligne,2).toString());
        } catch (ParseException ex) {
            Logger.getLogger(AjoutPatient.class.getName()).log(Level.SEVERE, null, ex);
        }
        date_acte.setDate(datt);
         cact=act[ligne];
         System.out.println(cact);
        
        
    }//GEN-LAST:event_jTable2MouseClicked
public void supprime_presenti(String dos, String ref, java.sql.Date dt) throws ClassNotFoundException, SQLException
{
    con=cnx.connect();
String req="delete from presAnti where dos like '"+dos+"%' and ref like '"+ref+"%' and dt='"+dt+"'";
Statement st=con.createStatement();
st.executeUpdate(req);

JOptionPane.showMessageDialog(null,"Suppression fait avec succée");



}

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
       java.sql.Date d =new java.sql.Date(date_anti.getDate().getTime());
       
        try {
            supprime_presenti(dos_pat.getText(),antibiotique.getSelectedItem().toString(),d);
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_jButton15ActionPerformed
String cact;
    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        try {
            // TODO add your handling code here:
            con=cnx.connect();
       
        java.sql.Date d =new java.sql.Date(date_acte.getDate().getTime());
       String req="delete from verifierActe where cacte='"+cact+"' and dos='"+txtdosacte.getText()+"' and dact='"+d+"'";
       Statement st = null;
       
            st.executeUpdate(req);
        } catch (SQLException ex) {
        } catch (ClassNotFoundException ex) {
        }

JOptionPane.showMessageDialog(null,"Suppression fait avec succée");
    }//GEN-LAST:event_jButton20ActionPerformed
String dat;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AjoutPatient().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(AjoutPatient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel affectact;
    private javax.swing.JTextField age;
    private javax.swing.JButton ajout_acte1;
    private javax.swing.JPanel ajout_antiPanel;
    private javax.swing.JComboBox antibiotique;
    private javax.swing.JButton antibiotique1;
    private javax.swing.JButton btnreset;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox cat;
    private javax.swing.JTextField cissue;
    private com.toedter.calendar.JDateChooser date_acte;
    private com.toedter.calendar.JDateChooser date_anti;
    private com.toedter.calendar.JDateChooser denth;
    private com.toedter.calendar.JDateChooser dentrea;
    private javax.swing.JTextField detorig;
    private javax.swing.JComboBox diag1;
    private javax.swing.JComboBox diag2;
    private javax.swing.JRadioButton dom;
    public javax.swing.JTextField dos_pat;
    public javax.swing.JTextField dosage;
    private javax.swing.JLabel dossierpatient;
    private javax.swing.JLabel dossierpatient1;
    public javax.swing.JTextField dsj;
    private com.toedter.calendar.JDateChooser dsortrea;
    private javax.swing.JButton gest_act;
    private javax.swing.JButton gest_pass1;
    private javax.swing.JRadioButton hop;
    public javax.swing.JTextField ind_pat2;
    private javax.swing.JLabel indicepatient;
    private javax.swing.JComboBox infection;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField knuas;
    private javax.swing.JComboBox listacte;
    private javax.swing.JComboBox listeprisant;
    private javax.swing.JTextField motif;
    public javax.swing.JTextField nom_pat;
    private javax.swing.JLabel nompatient;
    private javax.swing.JLabel nompatient1;
    private javax.swing.JTextField saps;
    private javax.swing.JTabbedPane tappedpane;
    private com.toedter.calendar.JDateChooser txt_dn;
    private javax.swing.JTextField txtdosacte;
    private javax.swing.JTextField txtdose;
    private javax.swing.JTextField txtind;
    private javax.swing.JTextField txtlibel;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtref;
    private javax.swing.JComboBox txtsex;
    // End of variables declaration//GEN-END:variables

    private void setIcone() {
       
       
       //setIconeImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("a.ico.ico"))); //To change body of generated methods, choose Tools | Templates.
    }
}
