/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfeapplication;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Vector;

/**
 *
 * @author Mounir
 */
public class Courbe2 extends javax.swing.JPanel {

    /**
     * Creates new form Courbe2
     */
    private Vector<Point> listePoints=new Vector<Point>();
	private double xMin;//=Double.MAX_VALUE;
	private double yMin;//=Double.MAX_VALUE;
	private double xMax;//=Double.MIN_VALUE;
	private double yMax;//=Double.MIN_VALUE;
 
	private int largeur=621;
	private int hauteur=424;
	private int left=50;
	private int top=50;
 
 /*JLabel lab1=new JLabel();
 JLabel lab2=new JLabel();
 JLabel lab3=new JLabel();
 JLabel lab4=new JLabel();
 JLabel lab5=new JLabel();
 JLabel lab6=new JLabel();
 JLabel lab7=new JLabel();*/
	public Courbe2(){
 
	}
 
	public void ajouterPoint(Point p){
		
			this.xMin=p.getX();
		
			this.xMax=p.getX();
 
		
			this.yMin=p.getY();
		
			this.yMax=p.getY();
 
		this.listePoints.add(p);
 
		this.repaint();		
	}
 
	public void paint(Graphics g){
            //super.paint(g);
             float[] dash4 = {4f, 4f, 1f};
             Graphics2D g2d = (Graphics2D) g.create();
 g.setColor(Color.red);
        g.drawLine(120,480,120,50);//X
        g.drawLine(120, 480,900, 480);
 
        

    /*    g.setColor(Color.black);
   g.drawLine(130, 60,120, 50);
        g.drawLine(110, 60,120, 50);
      
        g.drawLine(115, 360,125,360);
        g.drawLine(115, 240,125,240);
        g.drawLine(115, 120,125, 120);*/
 
        BasicStroke bs3 = new BasicStroke(1.5f, BasicStroke.CAP_SQUARE,
                                  BasicStroke.JOIN_MITER, 10.0f);
        // g.setStroke(bs3);
             BasicStroke bs4 = new BasicStroke(1, BasicStroke.CAP_BUTT,
                BasicStroke.JOIN_ROUND, 1.0f, dash4, 2f);
              g2d.setStroke(bs4);
        g2d.drawLine(220,480,220,50);
      
 g2d.setStroke(bs4);
        g2d.drawLine(320,480,320,50);
         g2d.setStroke(bs4);
        g2d.drawLine(420,480,420,50);
         g2d.setStroke(bs4);
        g2d.drawLine(520,480,520,50);
         g2d.setStroke(bs4);
        g2d.drawLine(620,480,620,50);
         g2d.setStroke(bs4);
         g2d.drawLine(720,480,720,50);
          g2d.setStroke(bs4);
        g2d.drawLine(820,480,820,50);
 
			
        }
 
	public Point convertirPointSurReferenciel(Point p){
		double amplitudeX=this.xMax-this.xMin;
		double amplitudeY=this.yMax-this.yMin;
 
		double rapportX=this.largeur/amplitudeX;
		double rapportY=this.hauteur/amplitudeY;
 
		double x=(p.getX()-this.xMin)*rapportX;
		double y=(p.getY()-this.yMin)*rapportY;
 
		y=this.hauteur-y;
 
		x=x+this.left;
		y=y+this.top;
 
		return new Point(x, y);
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
